// Do not edit. This file is machine generated by the Resource DLL Wizard.

library CCOWEmulator;

{ITE} {DFMFileType} {MainForm.dfm}
{ITE} {DFMFileType} {ServerModule.dfm}
{ITE} {DFMFileType} {SessionForm.dfm}
{ITE} {RCFileType} {CCOWEmulator_DRC.rc}

{$R 'MainForm.dfm' 'frmMain:TForm'}
{$R 'ServerModule.dfm' 'RestServer:TDataModule'}
{$R 'SessionForm.dfm' 'SessionForm:TForm'}
{$R 'CCOWEmulator_DRC.res' 'CCOWEmulator_DRC.rc'}

{$E ENU}

begin
end.
